workflows:
  android-build:
    name: Build Android App
    max_build_duration: 30
    environment:
      android_signing:
        - your_keystore_reference
      vars:
        PACKAGE_NAME: "com.arexperiments.justaline"  # replace with your actual package
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/*.apk
